import './globals.css';
import localFont from 'next/font/local';
import TanstackQueryProviders from '@/provider/tanstack-query-provider';
import LayoutWrapper from '@/shared/layout/layout-wrapper';
import Header from '@/shared/layout/header';
import Footer from '@/shared/layout/footer';

import type { Metadata } from 'next';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={pretendard.className}>
        <TanstackQueryProviders>
          <LayoutWrapper>
            <Header />
            <main className='px-4'>{children}</main>
            <Footer />
          </LayoutWrapper>
        </TanstackQueryProviders>
      </body>
    </html>
  );
}
