import './globals.css';
import TanstackQueryProviders from '@/provider/tanstack-query-provider';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <TanstackQueryProviders>{children}</TanstackQueryProviders>
      </body>
    </html>
  );
}
